runtime: nodejs14
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
env_variables:
  MONGODB_URI: "mongodb+srv://echarqaouiouissal:up6V2kZTP8raI1yw@cluster0.qjp9keg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"